### ISSUE TITLE
how do I get this to run

### ISSUE THREAD

**Issue by jaekim24** [sgelb/impositioner#12]
I'm running arch and I git cloned it to a directory. Now what, I've looked online and nothing helped. I really want this to work because I don't want to pay for a software. Can anyone help me?

**Comment by sgelb** [comment]
This project uses Poetry for dependency managment. 
After installing poetry and running `poetry install`, there are multiple possibilities to run impositioner. `poetry build`  builds an installable wheel. `poetry shell` puts you inside the venv where you can run `impositioner` without installing it system-wide.

I hope this helps you and therefor I close this ticket..
