### ISSUE TITLE
How do I flip the pages over the short edge instead of the long edge

### ISSUE THREAD

**Issue by jaekim24** [sgelb/impositioner#14]
So in the booklet the pages would flip upside down but I want the pages to be in the same orientation. I'm doing 2 pages on one sheet. I want to make like a magazine style book. So there would be two pages on the front and two on the back. So you would flip over the short edge to get to the back side of the page and the text would be right side up. Thank you.

**Comment by sgelb** [comment]
Do you have an example for a source pdf and the wanted result? Do I understand you correct, that you have an input pdf like you can create with `tools/pdfSampler.py --landscape 4 a5`? Would running `impositioner -b top a5_landscape_4.pdf` create your desired result?

ps. After updating the dependencies in a previous commit, I missed a bug in `pdfSampler.py`.  This is fixed in the latest change.

**Comment by jaekim24** [comment]
This is how it looks when I run "impositioner -s 24 -c -n 2 -f a4 book.pdf" . Notice the second page is upside down. 
![wrong](https://user-images.githubusercontent.com/62858192/185265444-aa0d5c85-ac0d-4d23-a886-343ea9ce766a.PNG)

This is the result that I want
![right](https://user-images.githubusercontent.com/62858192/185265529-6390792f-6f01-4083-a3e1-77ed2ff45b9f.PNG)

**Comment by sgelb** [comment]
Thanks for the examples.

I'm still not sure if I understand your use case. Do you want to print one-sided with an empty backside? Is your goal to make a booklet or to staple a stack of paper on one side? Why set a signature length? What about the "Pages per Side" option of your printing software? I would be happy if you could describe your use case in more detail.


Nevertheless, changing https://github.com/sgelb/impositioner/blob/d34e8668fc26870c9e3c110df34d6e1dd775e0fc/impositioner/core.py#L94

to 

```
sheets.append(merge((pages[i + 1], pages[half + i + 1]), rotation, binding))
```

would probably do the trick for you.

**Comment by jaekim24** [comment]
My goal is to make a booklet. I don't want to print one sided with an empty backside. I want to print on both sides. The front will have two pages and if you flip the paper over the short edge there will also be two pages. That is my goal. So I can have multiple signatures and create a book. To make one signature I would stack the papers and fold it in half. Right now the output of the program has it where I start at the front and the images are right side up and if I flip the paper over the short edge to get to the back the images looks upside down. I hope this helps you understand my goal. If not keep asking me question. Thank you for creating this program, it is amazing!

**Comment by sgelb** [comment]
Okay, so it is about the printing and not about the imposition. Can you try out that code change from my last comment and tell me if that is what you want? Would probably add a CLI argument for that in the future.
